language: go

go:
  - 1.13.x

install:
  - go get -v -t ./...
  - bash scripts/install_redis_6.sh

script:
  - /home/travis/gopath/src/github.com/iwanbk/rimcu/redis-unstable/src/redis-server&
  - go build ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
