name: Test and Linter
on: push

jobs:
  test:
    name: Test and Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run test and lint
        uses: ./.github/test_lint/
        env:
          TEST_REDIS_ADDRESS: redis:${{ job.services.redis.ports[6379] }}
    services:
      redis:
        image: redis:6.0-rc4-alpine
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
